// Arabic translations of API error messages. Unknown messages fall back to the original text.
const M: Record<string, string> = {
  "A product with this SKU already exists.": "يوجد منتج بنفس رمز SKU.",
  "A reason is required for manual adjustments.": "السبب مطلوب للتعديلات اليدوية.",
  "Access denied.": "ليست لديك صلاحية الوصول.",
  "Add a description and an address to your profile first.": "أضف وصفاً وعنواناً لملف مصنعك أولاً.",
  "Adjustment would drop stock below the reserved quantity.": "التعديل سيجعل المخزون أقل من الكمية المحجوزة.",
  "Adjustment would make stock negative.": "التعديل سيجعل المخزون بالسالب.",
  "An account with this email already exists.": "يوجد حساب مسجّل بهذا البريد الإلكتروني.",
  "Category not found.": "التصنيف غير موجود.",
  "Certification name is required.": "اسم الشهادة مطلوب.",
  "Certification not found.": "الشهادة غير موجودة.",
  "Factory name and region are required.": "اسم المصنع والمنطقة مطلوبان.",
  "Factory not found.": "المصنع غير موجود.",
  "File is larger than 5 MB.": "حجم الملف أكبر من 5 ميغابايت.",
  "Incorrect email or password.": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  "Inspection not found.": "عملية الفحص غير موجودة.",
  "Insufficient finished-goods stock to ship this order.": "المخزون الجاهز لا يكفي لشحن هذا الطلب.",
  "Invalid account type.": "نوع الحساب غير صالح.",
  "Invalid date.": "التاريخ غير صالح.",
  "Invalid email.": "البريد الإلكتروني غير صالح.",
  "Invalid failed quantity.": "كمية الراسب غير صالحة.",
  "Invalid file URL.": "رابط الملف غير صالح.",
  "Invalid logo URL.": "رابط الشعار غير صالح.",
  "Invalid passed quantity.": "كمية الناجح غير صالحة.",
  "Invalid quantity.": "الكمية غير صالحة.",
  "Invalid unit price.": "سعر الوحدة غير صالح.",
  "MOQ must be a positive integer.": "الحد الأدنى للطلب يجب أن يكون عدداً صحيحاً موجباً.",
  "Message is empty.": "الرسالة فارغة.",
  "Message is too long.": "الرسالة طويلة جداً.",
  "Name cannot be empty.": "الاسم لا يمكن أن يكون فارغاً.",
  "Name is required.": "الاسم مطلوب.",
  "No file provided.": "لم يتم اختيار ملف.",
  "No offer to accept.": "لا يوجد عرض لقبوله.",
  "Only PNG, JPEG, WebP or PDF files are allowed.": "المسموح فقط: PNG وJPEG وWebP وPDF.",
  "Only confirmed orders can start production.": "يمكن بدء الإنتاج للطلبات المؤكدة فقط.",
  "Only orders that are ready to ship can be shipped.": "يمكن شحن الطلبات الجاهزة للشحن فقط.",
  "Only pending factories can be reviewed.": "يمكن مراجعة المصانع قيد الانتظار فقط.",
  "Only shipped orders can be confirmed.": "يمكن تأكيد استلام الطلبات المشحونة فقط.",
  "Order not found.": "الطلب غير موجود.",
  "Passed + failed must equal inspected quantity.": "مجموع الناجح والراسب يجب أن يساوي الكمية المفحوصة.",
  "Password must be at least 8 characters.": "كلمة المرور يجب ألا تقل عن 8 أحرف.",
  "Product not found for this factory.": "المنتج غير موجود لدى هذا المصنع.",
  "Product not found.": "المنتج غير موجود.",
  "Production is not in progress.": "الإنتاج ليس قيد التنفيذ.",
  "Production not found.": "أمر الإنتاج غير موجود.",
  "Quotation not found.": "عرض السعر غير موجود.",
  "Region cannot be empty.": "المنطقة لا يمكن أن تكون فارغة.",
  "This inspection has already been processed.": "تمت معالجة هذا الفحص مسبقاً.",
  "This offer has expired.": "انتهت صلاحية هذا العرض.",
  "This quotation cannot be answered now.": "لا يمكن الرد على عرض السعر هذا الآن.",
  "This quotation is closed.": "عرض السعر هذا مغلق.",
  "Unauthorized.": "غير مصرّح لك بهذا الإجراء.",
  "Upload at least one certification document first.": "ارفع مستند شهادة واحداً على الأقل أولاً.",
  "Verification is already pending or approved.": "طلب التوثيق قيد المراجعة أو تم اعتماده.",
  "Waiting for the factory's quotation.": "بانتظار عرض سعر المصنع.",
  "Waiting for the other party to respond.": "بانتظار رد الطرف الآخر.",
  "Website must start with http:// or https://": "الموقع يجب أن يبدأ بـ http:// أو https://",
  "You cannot accept your own offer.": "لا يمكنك قبول عرضك أنت.",
  "action must be ACCEPT or REJECT.": "الإجراء يجب أن يكون قبول أو رفض.",
  "action must be APPROVE or REJECT.": "الإجراء يجب أن يكون اعتماد أو رفض.",
  "delta must be a non-zero integer.": "التغيير يجب أن يكون عدداً صحيحاً غير صفر.",
  "factoryId and a positive integer quantity are required.": "المصنع وكمية صحيحة موجبة مطلوبان.",
  "factoryId is required.": "المصنع مطلوب.",
  "name, sku and categoryId are required.": "الاسم ورمز SKU والتصنيف مطلوبة.",
  "producedQuantity must be a positive integer.": "الكمية المنتجة يجب أن تكون عدداً صحيحاً موجباً.",
  "Admin accounts cannot be deleted here.": "لا يمكن حذف حساب الإدارة من هنا.",
  "Incorrect password.": "كلمة المرور غير صحيحة.",
  "You have active orders. Finish or cancel them before deleting your account.": "لديك طلبات نشطة. أنهِها أو ألغِها قبل حذف حسابك.",
  "Type the confirmation word.": "اكتب كلمة التأكيد.",
  "Mobile phone number is required.": "رقم الموبايل مطلوب.",
  "Invalid mobile phone number. Use digits with an optional country code, e.g. +962791234567.": "رقم الموبايل غير صالح. استخدم أرقاماً مع رمز الدولة اختيارياً، مثل +962791234567.",
  "Commercial registration number is required.": "رقم السجل التجاري مطلوب.",
  "Invalid commercial registration number.": "رقم السجل التجاري غير صالح.",
  "Tax number is required.": "الرقم الضريبي مطلوب.",
  "Invalid tax number.": "الرقم الضريبي غير صالح.",
  "This commercial registration number is already registered.": "رقم السجل التجاري هذا مسجّل مسبقاً بحساب آخر. لا يُسمح بأكثر من حساب لنفس السجل.",
  "Registration and tax numbers cannot be changed once saved. Contact support.": "لا يمكن تعديل السجل والرقم الضريبي بعد حفظهما. راسل الإدارة.",
  "Add your commercial registration and tax numbers to your profile first.": "أضف السجل التجاري والرقم الضريبي إلى ملفك أولاً.",
  "Email not verified.": "يجب توثيق بريدك الإلكتروني أولاً.",
  "Use Latin digits (0-9) only.": "استخدم الأرقام اللاتينية (0-9) فقط.",
  "Please wait before requesting another code.": "انتظر دقيقة قبل طلب رمز جديد.",
  "Could not send the verification email. Try again later.": "تعذّر إرسال بريد التحقق. حاول لاحقاً.",
  "Verification code must be 6 digits (Latin 0-9).": "رمز التحقق من 6 أرقام لاتينية (0-9).",
  "Code expired or not found. Request a new one.": "الرمز منتهي أو غير موجود. اطلب رمزاً جديداً.",
  "Too many attempts. Request a new code.": "محاولات كثيرة. اطلب رمزاً جديداً.",
  "Incorrect verification code.": "رمز التحقق غير صحيح.",
  "Could not send the WhatsApp message. Try again later.": "تعذّر إرسال رسالة واتساب. حاول لاحقاً أو استخدم البريد الإلكتروني.",
  "WhatsApp verification is not available.": "التحقق عبر واتساب غير متاح حالياً.",
  "No phone number on this account.": "لا يوجد رقم هاتف مسجّل لهذا الحساب.",
  "Invalid country.": "الدولة غير صالحة.",
  "Phone number does not match the selected country.": "رقم الهاتف لا يطابق رمز الدولة المختارة.",
  "Description is required (20 to 1000 characters).": "الوصف مطلوب (من 20 إلى 1000 حرف).",
  "Authentication required.": "يجب تسجيل الدخول أولاً.",
  "Internal server error.": "حدث خطأ في الخادم.",
};

export function ar(message: string): string {
  if (M[message]) return M[message];
  let m = message.match(/^Minimum order quantity is (\d+)\.$/);
  if (m) return `الحد الأدنى للطلب هو ${m[1]}.`;
  m = message.match(/^Exceeds plan: (\d+) units remaining\.$/);
  if (m) return `يتجاوز الخطة: المتبقي ${m[1]} وحدة.`;
  return message;
}
